// Landing page icon barrel — re-exports from lucide-react
export type { LucideIcon } from 'lucide-react';
export {
  GraduationCap,
  BookOpen,
  Building2,
  Calculator,
  Atom,
  FlaskConical,
  Briefcase,
  TrendingUp,
  Monitor,
  Pencil,
  Compass,
  Award,
  CheckCircle2,
  Facebook,
  Instagram,
  Twitter,
  ChevronDown,
  ArrowRight,
  ClipboardList,
  FolderOpen,
  CalendarDays,
  Users,
  Menu,
  X,
  HardHat,
  HeartPulse,
  Wrench,
  Bell,
  Sparkles,
} from 'lucide-react';
